services:
  - type: web
    name: air-hockey-online-kaleido1
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: HOST
        value: 0.0.0.0
